---
language: ruby
sudo: false
before_install:
  # TODO: Remove along with all BUNDLER_VERSION hackery once support for
  # Vagrant < 1.9 is dropped.
  #
  # Travis has taken to installing Bundler as a "default" gem which locks
  # it down and makes it extremely frustrating to use a different version.
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler --version $BUNDLER_VERSION
install: bundle _${BUNDLER_VERSION}_ install --without development
script: bundle _${BUNDLER_VERSION}_ exec rspec --color --format documentation
notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
    - rvm: 2.0.0
      env: TEST_VAGRANT_VERSION=v1.7.4 BUNDLER_VERSION=1.10.5
    - rvm: 2.2.5
      env: TEST_VAGRANT_VERSION=v1.8.7 BUNDLER_VERSION=1.12.5
    - rvm: 2.3.4
      env: TEST_VAGRANT_VERSION=v1.9.8 BUNDLER_VERSION=1.16.1
    - rvm: 2.4.3
      env: TEST_VAGRANT_VERSION=HEAD BUNDLER_VERSION=1.16.1
